import pathlib,json,hashlib,struct
root=pathlib.Path('.'); owned=root/'deliveries/completion-audits/FINISH-B1/2026-10-10-r1'; delivery=root/'deliveries/FINISH-B1'; declared=json.loads((delivery/'output-hashes.json').read_text())['outputs']; mismatches=[]
for name,meta in declared.items():
 p=delivery/name; actual=hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else None
 if actual!=meta['sha256'] or (p.exists() and p.stat().st_size!=meta['byteSize']): mismatches.append({'path':name,'expected':meta,'actualSha256':actual,'actualBytes':p.stat().st_size if p.exists() else None})
models=[]; required=['Door_Frame','Door_Leaf','Door_Hinge','Plant_Leaf_01','Plant_Leaf_02','Books_Stack','Chair_Seat','PC_Fan_Group','Zenith_Core','Camera_Lens_Ring','Mic_LED','Clock_Face']
for p in (delivery/'assets').glob('*.glb'):
 b=p.read_bytes(); j=json.loads(b[20:20+struct.unpack_from('<I',b,12)[0]]); names=[n.get('name') for n in j.get('nodes',[])]; models.append({'file':p.name,'bytes':len(b),'missingRequired': [n for n in required if n not in names],'nodes':[{ 'name':n.get('name'),'translation':n.get('translation'),'children':n.get('children')}for n in j['nodes'] if n.get('name') in required+['chair-root','resident','door-hinge','chair_swivel_pivot']],'clips':[{'name':a.get('name'),'duration':max(j['accessors'][s['input']].get('max',[0])[0]for s in a['samplers']),'targets':sorted(set(j['nodes'][c['target']['node']].get('name','')for c in a['channels']))}for a in j.get('animations',[])],'allNodeNames':names})
files=list(delivery.rglob('*')); excluded=[str(p.relative_to(delivery))for p in files if p.is_file() and str(p.relative_to(delivery)).replace('\\','/')not in declared]
result={'declaredOutputs':len(declared),'hashMismatches':mismatches,'notInDeclaredOutputs':excluded,'models':models};(owned/'asset-hash-binding-proof.json').write_text(json.dumps(result,indent=2)+'\n'); print(json.dumps({'declaredOutputs':len(declared),'mismatches':mismatches,'excluded':excluded,'roomMissing':models[0]['missingRequired']}))
inputs=[p for p in files if p.is_file()]+[root/'AGENTS.md',root/'START_HERE.md',root/'references/images/main-reference.png',root/'docs/planning/reconciliation-packets/finish-contracts/00-contract-decision.md',root/'docs/planning/reconciliation-packets/finish-contracts/05-maker-packets.md',root/'docs/planning/reconciliation-packets/2026-10-10-completion-recheck.md'];(owned/'input-hashes.json').write_text(json.dumps({str(p).replace('\\','/'):hashlib.sha256(p.read_bytes()).hexdigest()for p in inputs},indent=2)+'\n')
