from pathlib import Path
import json,hashlib,datetime,platform,subprocess
OUT=Path(__file__).resolve().parent
ROOT=OUT.parents[4]
def record(p):
 b=p.read_bytes();return {'path':p.relative_to(ROOT).as_posix(),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def write(name,value): (OUT/name).write_text(json.dumps(value,indent=2)+'\n',encoding='utf-8')
initial=json.loads((OUT/'before-contracts/input-hashes.json').read_text(encoding='utf-8'))
extra=['app/tests/unit/contract-types.test.ts','app/tests/fixtures/engineering-section-4.ts','app/tsconfig.json','app/src/server/auth/require-owner.ts','app/src/server/auth/page-owner.ts','app/src/server/jobs/runner.ts','app/src/features/experience/interaction-registry.ts','app/src/features/portfolio/case-study.tsx','app/src/server/content/revisions.ts','app/src/server/content/publish.ts','app/src/content/publication-reader.ts','app/src/content/server-publication.ts','app/src/server/media/manifest.ts','app/src/server/operations/backup-restore.ts']
write('input-hashes.json',{'packet':'FINISH-00-R2','reviewRevision':'independent/r1','hashPolicy':'SHA-256 of raw bytes','contractInputManifest':record(OUT/'before-contracts/input-hashes.json'),'contractOutputManifest':record(OUT/'before-contracts/output-hashes.json'),'identityCheckedInputs':initial['inputs'],'additionalDirectlyInspectedInputs':[record(ROOT/p) for p in extra],'inspectionPolicy':'Identity-check entries do not claim every input was completely read; report identifies direct relevant section inspection.'})
identity=json.loads((OUT/'identity-results.json').read_text())
write('audit.json',{'packet':'FINISH-00-R2','revision':'independent/r1','advice':'REWORK','scope':'Initial architecture/design contract consistency; no maker implementation acceptance','reviewer':{'task':'/root/r2_independent_audit','invocationModel':'gpt-6.1-sol','invocationReasoningEffort':'ultra','forkTurns':'none','identitySource':'Parent-confirmed actual collaboration invocation metadata','servingBackendIntrospection':False,'separatePaidAccountClaim':False},'candidate':identity,'findings':[{'id':'R2-AUD-01','severity':'HIGH','status':'CONFIRMED','owner':'Parent','summary':'C2 required reveal/greeting presets lack CameraPreset/types allowance'},{'id':'R2-AUD-02','severity':'HIGH','status':'CONFIRMED','owner':'Parent','summary':'A2/C2 exact type fixtures/tests unallocated; ACTIVATE_OBJECT payload undefined'},{'id':'R2-AUD-03','severity':'HIGH','status':'CONFIRMED','owner':'Parent','summary':'Conflicting Door_Frame/Door_Hinge parent hierarchy'},{'id':'R2-AUD-04','severity':'MEDIUM','status':'CONFIRMED','owner':'Parent','summary':'C3 tier-control wording exceeds framing/layout allowance'}],'evidence':{'hashSizeChecks':{'pass':159,'total':159},'allowlistTableRows':129,'sqlMigrations':3,'publicApplicationTables':16,'glbFilesParsed':7,'compilerDefectsReproduced':3,'compilerScope':'Minimal synthetic proposed-type deltas derived from real canonical declarations; not full successor build','productionChanges':0,'commits':0},'notRun':['app/successor broad suites/build','browser/WebGL/device/assistive behavior','native Blender export','native provider/Auth/Storage/mail/scheduler/rollback/disaster recovery','hosted CI','external Gemini dispatch'],'next':'Parent correction followed by exact-bound independent P22 delta; Parent retains acceptance authority'})
write('command-receipts.json',{'workingDirectory':str(ROOT),'pythonVersion':platform.python_version(),'commands':[{'command':'python deliveries/completion-audits/FINISH-00-R2/independent/r1/inspect_identity.py','exitCode':0,'timestampUTC':identity['timestampUTC'],'result':'identity-results.json; manifest-verification.json; path-state-results.json; sql-inventory-results.json; glb-inventory-results.json'},{'command':'node deliveries/completion-audits/FINISH-00-R2/independent/r1/type-seam-probe.mjs','attempt':1,'exitCode':1,'result':'type-seam-first-attempt.json'},{'command':'node deliveries/completion-audits/FINISH-00-R2/independent/r1/type-seam-probe.mjs','attempt':2,'exitCode':1,'result':'type-seam-second-attempt.json'},{'command':'node deliveries/completion-audits/FINISH-00-R2/independent/r1/type-seam-probe.mjs','attempt':3,'exitCode':0,'timestampUTC':'2026-10-10T11:30:29.606Z','result':'type-seam-results.json','interpretation':'DEFECT REPRODUCED: three intended compiler failures'}],'readOnlyProbes':['git rev-parse HEAD','git rev-parse HEAD:app','git diff f62a43c5e71c00dcb89e28275ea81d842167db80 -- app','rg/read direct named source','main-reference.png view_image'],'failedReadProbes':['app/src/server/media/storage.ts','app/src/server/operations/job-runner.ts','app/src/server/auth/owner.ts'],'failedReadDisposition':'Not inspected; actual source resolved with rg and named in report.'})
write('output-hashes.json',{'packet':'FINISH-00-R2','reviewRevision':'independent/r1','hashPolicy':'SHA-256 of raw bytes','exclusions':['this root output-hashes.json (self-reference)','__pycache__ (interpreter cache)'],'outputs':[record(p) for p in sorted(OUT.rglob('*')) if p.is_file() and p!=OUT/'output-hashes.json' and '__pycache__' not in p.parts]})
print(json.dumps({'advice':'REWORK','report':record(OUT/'report.md'),'audit':record(OUT/'audit.json'),'inputManifest':record(OUT/'input-hashes.json'),'outputManifest':record(OUT/'output-hashes.json')},indent=2))
