import pathlib,json,struct,hashlib,subprocess
root=pathlib.Path('.'); out=root/'deliveries/audits/2026-10-09-completion/world'; inputs=['AGENTS.md','START_HERE.md','docs/superpowers/specs/2026-09-30-yor-world-design.md','docs/planning/art-and-experience.md','docs/planning/interaction-catalog.md','docs/planning/validation-and-production.md','docs/planning/engineering-and-content.md','docs/planning/delegation-and-work-orders.md','docs/planning/reconciliation-packets/2026-10-09-completion-audit.md','docs/planning/current-status.json','docs/planning/reviews/2026-10-08-rc6-r1.md','references/README.md','references/manifest.json','references/images/main-reference.png','deliveries/production-environment/report.md','deliveries/production-environment/manifest.json','deliveries/production-environment/source/build-environment.py']
inputs += [str(p).replace('\\','/') for p in (root/'app/src/features/world').glob('*') if p.is_file()]
inputs += ['app/src/features/room/painting-controller.ts','app/src/features/room/environment-controller.ts','app/src/features/room/room-controls.tsx','app/src/features/experience/controller.ts','app/src/features/experience/interaction-registry.ts','app/src/features/experience/project-transition.ts','app/src/features/experience/audio.ts','app/src/features/character/greeting-controller.ts','app/src/features/monitor/launcher.tsx','app/tests/e2e/physical-interactions.spec.ts','app/tests/integration/runtime/frozen-world-binding.test.ts']
inputs += ['deliveries/G6/full-stack-integration/evidence/graphics-diagnostics/default-gpu-calibrated-lighting/high-home-ui.png','deliveries/G6/full-stack-integration/evidence/graphics-diagnostics/default-gpu-calibrated-lighting/high-home-canvas-bitmap.png','deliveries/A3/evidence/screenshots/10-mobile-viewport.png','deliveries/production-environment/renders/blender-mobile-portrait.png']
models=[]
for name in ['production-room-full.glb','resident-production.glb','fixture-production.glb','interaction-assets.glb']:
 p=root/'app/public/models'/name; b=p.read_bytes(); j=json.loads(b[20:20+struct.unpack_from('<I',b,12)[0]]); inputs.append(str(p).replace('\\','/')); models.append({'path':str(p),'bytes':len(b),'nodes':len(j.get('nodes',[])),'meshes':len(j.get('meshes',[])),'animations':[{'name':a.get('name'),'channels':len(a['channels']),'targets':sorted(set(j['nodes'][c['target']['node']].get('name','') for c in a['channels']))} for a in j.get('animations',[])],'hexPanels':[n.get('name') for n in j.get('nodes',[]) if 'hex_panel' in n.get('name','')]})
(out/'asset-inspection.json').write_text(json.dumps(models,indent=2)+'\n')
(out/'input-hashes.json').write_text(json.dumps({p:hashlib.sha256(root.joinpath(p).read_bytes()).hexdigest() for p in inputs},indent=2)+'\n')
print(json.dumps({'head':subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip(),'appTree':subprocess.check_output(['git','rev-parse','HEAD:app'],text=True).strip(),'modelAnimations':[(m['path'],[a['name'] for a in m['animations']]) for m in models]},indent=2))
